### ISSUE TITLE
Magnetic field issue

### ISSUE THREAD

**Issue by patrikthunstrom** [JohanSchott/impurityModel#1]
There is a small bug in get_spectrum and get_spectrum_using_CF. The magnetic field hx is overwritten by hy in the following lines:

        hHfieldOperator[(((l, 1, m), 'c'), ((l, 0, m), 'a'))] = hx*1/2.
        hHfieldOperator[(((l, 0, m), 'c'), ((l, 1, m), 'a'))] = hx*1/2.
        hHfieldOperator[(((l, 1, m), 'c'), ((l, 0, m), 'a'))] = -hy*1/2.*1j
        hHfieldOperator[(((l, 0, m), 'c'), ((l, 1, m), 'a'))] = hy*1/2.*1j

/Patrik

**Comment by JohanSchott** [comment]
Great that you found this bug. Thanks!
In https://github.com/JohanSchott/impurityModel/pull/2 the bug should be fixed.
